
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label titleLbl;
	private global::Gtk.HBox inputHBox;
	private global::Gtk.Label wordLbl;
	private global::Gtk.Alignment wordEntryAlignment;
	private global::Gtk.Entry wordEntry;
	private global::Gtk.Alignment lookupBtnAlignment;
	private global::Gtk.Button lookupBtn;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Polish Word Lookup");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(2));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.titleLbl = new global::Gtk.Label ();
		this.titleLbl.Name = "titleLbl";
		this.titleLbl.Xpad = 6;
		this.titleLbl.Ypad = 6;
		this.titleLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Look up a word to find its meaning.");
		this.vbox1.Add (this.titleLbl);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.titleLbl]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.inputHBox = new global::Gtk.HBox ();
		this.inputHBox.Name = "inputHBox";
		this.inputHBox.Spacing = 6;
		// Container child inputHBox.Gtk.Box+BoxChild
		this.wordLbl = new global::Gtk.Label ();
		this.wordLbl.Name = "wordLbl";
		this.wordLbl.Xpad = 6;
		this.wordLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Word:");
		this.inputHBox.Add (this.wordLbl);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.inputHBox [this.wordLbl]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child inputHBox.Gtk.Box+BoxChild
		this.wordEntryAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.wordEntryAlignment.Name = "wordEntryAlignment";
		this.wordEntryAlignment.RightPadding = ((uint)(6));
		// Container child wordEntryAlignment.Gtk.Container+ContainerChild
		this.wordEntry = new global::Gtk.Entry ();
		this.wordEntry.CanFocus = true;
		this.wordEntry.Name = "wordEntry";
		this.wordEntry.IsEditable = true;
		this.wordEntry.InvisibleChar = '•';
		this.wordEntryAlignment.Add (this.wordEntry);
		this.inputHBox.Add (this.wordEntryAlignment);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.inputHBox [this.wordEntryAlignment]));
		w4.Position = 1;
		this.vbox1.Add (this.inputHBox);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.inputHBox]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lookupBtnAlignment = new global::Gtk.Alignment (1F, 0F, 0F, 1F);
		this.lookupBtnAlignment.Name = "lookupBtnAlignment";
		this.lookupBtnAlignment.RightPadding = ((uint)(6));
		this.lookupBtnAlignment.BottomPadding = ((uint)(6));
		// Container child lookupBtnAlignment.Gtk.Container+ContainerChild
		this.lookupBtn = new global::Gtk.Button ();
		this.lookupBtn.CanFocus = true;
		this.lookupBtn.Name = "lookupBtn";
		this.lookupBtn.UseUnderline = true;
		this.lookupBtn.Label = global::Mono.Unix.Catalog.GetString ("Lookup");
		this.lookupBtnAlignment.Add (this.lookupBtn);
		this.vbox1.Add (this.lookupBtnAlignment);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lookupBtnAlignment]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 248;
		this.DefaultHeight = 132;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.lookupBtn.Clicked += new global::System.EventHandler (this.OnLookupBtnClicked);
	}
}
