
// This file has been generated by the GUI designer. Do not modify.
namespace PolWordLookup
{
	public partial class ResultWindow
	{
		private global::Gtk.VBox mainVBox;
		private global::Gtk.HBox wordHBox;
		private global::Gtk.Label resultTitleLbl;
		private global::Gtk.Label resultForWordLbl;
		private global::Gtk.Alignment mainTextAlignment;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView definitionTxt;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PolWordLookup.ResultWindow
			this.Name = "PolWordLookup.ResultWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Your Results");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child PolWordLookup.ResultWindow.Gtk.Container+ContainerChild
			this.mainVBox = new global::Gtk.VBox ();
			this.mainVBox.Name = "mainVBox";
			this.mainVBox.Spacing = 6;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.wordHBox = new global::Gtk.HBox ();
			this.wordHBox.Name = "wordHBox";
			this.wordHBox.Spacing = 6;
			// Container child wordHBox.Gtk.Box+BoxChild
			this.resultTitleLbl = new global::Gtk.Label ();
			this.resultTitleLbl.Name = "resultTitleLbl";
			this.resultTitleLbl.Xpad = 6;
			this.resultTitleLbl.Ypad = 6;
			this.resultTitleLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Result for word:");
			this.wordHBox.Add (this.resultTitleLbl);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.wordHBox [this.resultTitleLbl]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child wordHBox.Gtk.Box+BoxChild
			this.resultForWordLbl = new global::Gtk.Label ();
			this.resultForWordLbl.Name = "resultForWordLbl";
			this.resultForWordLbl.Xpad = 6;
			this.resultForWordLbl.Ypad = 6;
			this.resultForWordLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("(unknown)");
			this.wordHBox.Add (this.resultForWordLbl);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.wordHBox [this.resultForWordLbl]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.mainVBox.Add (this.wordHBox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.wordHBox]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.mainTextAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.mainTextAlignment.Name = "mainTextAlignment";
			this.mainTextAlignment.LeftPadding = ((uint)(6));
			this.mainTextAlignment.RightPadding = ((uint)(6));
			this.mainTextAlignment.BottomPadding = ((uint)(6));
			// Container child mainTextAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.definitionTxt = new global::Gtk.TextView ();
			this.definitionTxt.CanFocus = true;
			this.definitionTxt.Name = "definitionTxt";
			this.GtkScrolledWindow.Add (this.definitionTxt);
			this.mainTextAlignment.Add (this.GtkScrolledWindow);
			this.mainVBox.Add (this.mainTextAlignment);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.mainTextAlignment]));
			w6.Position = 1;
			this.Add (this.mainVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 151;
			this.Show ();
		}
	}
}
